### ISSUE TITLE
License and contact

### ISSUE THREAD

**Issue by kequach** [asreview/asreview-simulation-time#1]
While examining this repository I noticed that there is no license added, as well as contact persons in case of questions. Since most of the asreview repositories use an Apache 2.0 license, I think this might also be a good fit here?
An example of how to use the code would also be good to add to the documentation.

**Comment by PeterLombaers** [comment]
Added license and contact in (0b173c0ae95a638935899767acd8bbd201524792). I left out a code example, because this can be implemented better in version 1 of asreview.
